---

- name: Borrar UCDAgent.ps1
  hosts: win_servers
  vars: 
    ansible_become_method: runas
    ansible_become_user: system

  tasks:
    - name: Crear carpeta Temp
      win_file:
        path: "C:/Temp"
        state: directory

    - name: Crear fichero UCDAgent.ps1
      win_file:
        path: "C:/Temp/UCDAgent.ps1"
        state: touch

