---

- name: Borrar UCDAgent.ps1
  hosts: win_servers
  vars: 
    ansible_become_method: runas
    ansible_become_user: system
  tasks:
    - name: crear fichero
      win_file:
        path: "C:/Temp/UCDAgent.ps1"
        state: touch
      become: yes
